### PR TITLE
Login auth and TLS certificate signing

### PR DESCRIPTION
**Pull request by matt8100**
- Added dependencies
  - bcrypt for user-database password comparison
  - cookie-parser for parsing request cookies
  - jsonwebtoken for creating authentication tokens
  - mysql for connecting to CloudClub website database
  - node-forge for generating keys and signing certificates
  - archiver for streaming generated zips
- Added routes
  - POST-login
    - Login which expects an email and password. If successfully authenticated, will provide an authentication token that lasts one day.
    - [x] Test created
  - GET-cert
    - Checks for a valid auth token before proceeding
    - Generates client keys and certificate, and signs the certificate with the server's private key. The email attribute of the client cert is set to the user's email, and it is set to expire in a year.
    - Responds with a JSON containing the client private key and certificate. At the moment, this contains line-ending symbols (`\r\n`).
       - If a `download` query parameter is provided with any value, a ZIP file containing `clientKey.key` and `clientCert.crt` is provided instead.
    - Confirmed the generated certificates as working with the MQTTS broker.
    - [x] Test created

~~No unit tests were created yet, since we don't have a test MySQL database to use. I was wondering if we should move to creating temporary in-memory databases for our unit tests.~~

### CODE REVIEW

**Comment by matt8100** [comment]
@harsimrat99 Forgot to ping you. Will a test MySQL database be created, or should an in-memory database be used? Also, should the response be a file download or JSON response?

**Comment by harsimrat99** [comment]
@matt8100 we should look into connecting to the same MySQL server being used for the website. I can create a test credentials db in it with fake logins. However, the original CC website logins should be used for production. The response should be a file download. I think it makes sense for now.

We should store the TLS certs, or at least not permanently. We can, however, provide a temporary link to download the TLS certs which once downloaded can be deleted leaving only 1 copy for the user.

**Comment by matt8100** [comment]
@harsimrat99 If we have them download it right away, why would we store them? Are you saying this route should only provide a download link and not a download?

**Comment by harsimrat99** [comment]
Hi @matt8100 , I was just suggesting that perhaps we can provide users with a download link. However, if this is causing extra complications I am all in for simply downloading the certificates.

**Comment by matt8100** [comment]
@harsimrat99 These secrets must be added to the repo
image

**Comment by harsimrat99** [comment]
@matt8100 could you please tell what should be the proper configuration for running tests on a local machine. I have added the required env. vars. to my .env file; however, I am seeing the following error. 
image

I do not have PRODUCTION set in the .env file. I think I still need to figure out how to get database access from GitHub Actions for the MySQL database because AWS restricts who can access MySQL database connections. I have added the repo. secrets.

We can skip the database checks on GH Actions in the meantime although we should continue writing them.

**Comment by matt8100** [comment]
@harsimrat99 A `JWT_KEY` env variable is required for encrypting the tokens. I just added a commit for the test to set it for itself.

**Review by harsimrat99 — APPROVED** [review]

**Pull request merged**
