### PR TITLE
Add environment variable to workflow

### PR DESCRIPTION
**Pull request by matt8100**
OK, I really hope this works this time. @harsimrat99 can you add the `URI_MONGO` environment variable as a repository secret called `TEST_URI_MONGO`?

### CODE REVIEW

**Comment by harsimrat99** [comment]
@matt8100 I have added the requested variables. Please let me know if I should change anything else.

**Comment by matt8100** [comment]
@harsimrat99 All that's left is to see if it works after merging

**Comment by harsimrat99** [comment]
@matt8100 can we re-run the workflow before merging?

**Comment by harsimrat99** [comment]
I do see that in the logs it is requesting for the URI_MONGO variable.
image

**Review by harsimrat99 — APPROVED** [review]

**Comment by matt8100** [comment]
@harsimrat99 Unfortunately GitHub doesn't have an easy way to test workflows without just making more PRs. This PR contains a commit to add the environment variable, so it needs to be merged to see if it works.

**Comment by harsimrat99** [comment]
Hmm. I understand and I see that this a but inconvenient. I did merge the branch, but I did not run the workflow again. I will try with the GitHub CLI and see if that works. I also saw the latest run, but that seemed to have failed, albeit due to a different issue.

**Pull request merged**
