### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by matt8100**
- Switch `formidable` back to GitHub repo.

This PR, despite being marked as ready, **should not** be merged until tests are passing. Currently, it looks like GitHub is not able to connect to the test MySQL database, probably due to being unauthorized. Maybe [this](https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions) can help? @harsimrat99

### CODE REVIEW

**Comment by harsimrat99** [comment]
> * Switch `formidable` back to GitHub repo.
> 
> This PR, despite being marked as ready, **should not** be merged until tests are passing. Currently, it looks like GitHub is not able to connect to the test MySQL database, probably due to being unauthorized. Maybe [this](https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions) can help? @harsimrat99

Hi Matt,
Thank you for sharing the link for the GH Marketplace extension. I have looked into the action and it seems as if it is used for configuring AWS environment variables. 

I would like to point out that RDS instances can be connected from any whitelisted IP addresses in the security group. This means that you must initiate the connection from a registered IP address otherwise the connection will not be allowed.

I am thinking that there are a couple of ways to counter this issue:

1. Whitelist all IP address ranges to provide DB access from anywhere.
2. Deploy a lightweight testing database on EC2 and allow access to it from anywhere.
3. Deploy a testing database similar to what was used in the early days of cloud-club-website.
4. Whitelist GH Actions IP addresses during tests. Remove them afterwards via APIs. 

Let me know your thoughts.

**Comment by harsimrat99** [comment]
I have just updated the variables with a test database.

**Comment by matt8100** [comment]
@harsimrat99 Myself and GitHub can no longer connect to the test database.

**Comment by harsimrat99** [comment]
> @harsimrat99 Myself and GitHub can no longer connect to the test database.

Hi @matt8100 ,
Thank you for bringing the database issue to my attention. Unfortunately, the SQL service account has expired and it is no longer available. I am looking into deploying a permanent test DB on the VM. I will keep you informed about any changes. I understand that the tests will fail due to this, but in the meantime feel free to create a test database using that SQL service. (The only downside to that is that you have to manually enter a captcha every week. I forgot about it, and I am also out of email addresses.)

**Comment by harsimrat99** [comment]
@CloudClub-uoft/backend please take note of the database issue as commented above.

**Comment by matt8100** [comment]
@harsimrat99 what about using temporary in-memory databases for testing?

**Comment by harsimrat99** [comment]
> @harsimrat99 what about using temporary in-memory databases for testing?

@matt8100 I think that can be a potential solution. Are you suggesting something like an SQLite DB that is spun up during the tests? If so, then I think we should look into those.

**Comment by matt8100** [comment]
> > @harsimrat99 what about using temporary in-memory databases for testing?
> 
> @matt8100 I think that can be a potential solution. Are you suggesting something like an SQLite DB that is spun up during the tests? If so, then I think we should look into those.

Yes, that's what I'm thinking. We could also do the same for MongoDB as well. Let me know if I should go ahead with that.

**Comment by harsimrat99** [comment]
> Yes, that's what I'm thinking. We could also do the same for MongoDB as well. Let me know if I should go ahead with that.

Hi Matt,
I think we should go ahead with the SQLite database for tests. However, let's leave the MongoDB tests as they are for now.
Thank you.

**Comment by harsimrat99** [comment]
I am not sure what the implications of spinning up a test database in GH Actions will be, but let's see if it causes any problems. 

I understand that we want to automate testing but let's be wary of adding additional complexity and try to keep things as simple as possible. Maintaining tests should not distract us from maintaining the rest of the codebase. 

However, an idea I had was that if we wish to store some data for testing in the in-memory DB, then we could store an SQL dump in S3, and pull it during testing if required.

**Comment by harsimrat99** [comment]
@matt8100  would you like this PR to be merged?

**Comment by matt8100** [comment]
> @matt8100  would you like this PR to be merged?

No, since tests are not yet working

**Comment by matt8100** [comment]
I don't see how in-memory temporary databases will add any significant complexity. Can you elaborate?

**Comment by harsimrat99** [comment]
> I don't see how in-memory temporary databases will add any significant complexity. Can you elaborate?

Sure. I guess my concern is that we might not have the ability to launch a MongoDB instance during testing. (Since it's an entirely new OS process and GH Actions may limit memory provided during a CI flow).

By complexity I mean that I do not wish to create extra burden for the developers (you, and the rest of the team) to create the code as well as elaborate testing. However, if you think that this is a doable task, then by all means go ahead. I hope I have clarified your concerns and my thoughts.

**Comment by matt8100** [comment]
@harsimrat99 Tests fixed by running Mongo and MySQL docker services to serve as the test databases.

[GitHub Actions Usage Limits](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration#usage-limits)

**Comment by harsimrat99** [comment]
Hi @matt8100,
Thank you for getting this PR so far along. I think that the new test suites are a valuable addition to the repository.

**Review by harsimrat99 — APPROVED** [review]

**Pull request merged**
