### PR TITLE
S3 test fix

### PR DESCRIPTION
**Pull request by Golem8**
Probably fixes the s3 test, although I am not able to test the auto-checker locally.
Additionally, the s3 client object is now created once when the app is run. This way, a new s3 client does not have to be created every time a s3 request is made. It is like the mongo connection now, it is opened once.

### CODE REVIEW

**Comment by Golem8** [comment]
@harsimrat99 It seems the bucket still cannot be found

**Comment by Golem8** [comment]
Perhaps the secrets have different names in the repository? 
Right now, I am assuming they are the same as in the .env file
```URI_MONGO: ${{ secrets.TEST_URI_MONGO }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}```

**Comment by harsimrat99** [comment]
> Probably fixes the s3 test, although I am not able to test the auto-checker locally.
> Additionally, the s3 client object is now created once when the app is run. This way, a new s3 client does not have to be created every time a s3 request is made. It is like the mongo connection now, it is opened once.

Hi Simon, 
Thank you for making the changes, and for optimizing the S3 client so that we have a persistent connection from the start. I believe this will be much more efficient than recreating a connection each time. 

Regarding the S3 bucket test in GitHub Actions, I am going to spend some time on this issue and I will keep you updated. Actually, @matt8100 was also facing a similar issue a couple weeks ago where the MONGO_URI parameter was not being found and I believe some specific configuration had to be done to get the repo secrets to be viewable.

**Review by harsimrat99 — APPROVED** [review]

**Comment by harsimrat99** [comment]
@Golem8 I have updated the repository secrets and I believe the tests should pass now. It would be great if you could please try making another PR for verification.

**Comment by harsimrat99** [comment]
I will close this PR because I have made some changes to the s3-test-fix branch and I will create another PR to check for the CI.

**Pull request closed without merging**
