### PR TITLE
Add CORS support

### PR DESCRIPTION
**Pull request by matt8100**
Add CORS support again with credentials enabled.

As the React frontend is using the ES6 `fetch()` API, the `credentials: 'include'` property must be passed with requests. @iWebster28 @AdamS260 give it a shot and let me know how it goes.

### CODE REVIEW

**Review by harsimrat99 — APPROVED** [review]

**Comment by harsimrat99** [comment]
The first login request should not include the credentials: 'include' property. Only subsequent requests to data APIs should include it.

For example:

Step 1: fetch ('localhost:81/api/auth/login', options)
Step 2: add the credentials: 'include' property to options.
Step 3: fetch ('localhost:81/device/info')

The third step automatically includes the token after setting the credentials property to 'include'.

@matt8100, currently I have to add the following line in App.js (backend)
require('./util/router').boot(webApp, 'device');

This will allow the following APIs to be accessible by the React frontend:
image

We should move the routes/api/auth folder into routes/device folder to make the login route as well as the register, get info, etc. routes accessible by the frontend.

**Comment by matt8100** [comment]
> @matt8100, currently I have to add the following line in App.js (backend)
> require('./util/router').boot(webApp, 'device');
> 
> This will allow the following APIs to be accessible by the React frontend:
> image
> 
> We should move the routes/api/auth folder into routes/device folder to make the login route as well as the register, get info, etc. routes accessible by the frontend.

That is the whole point of the nginx reverse proxy though? You aren't supposed to access device routes through the webapp server. The `/api` group of routes is already accessible by the frontend, those are the routes for the frontend, not device. We should instead be moving the routes for the frontend that are incorrectly in the `device` folder to the `api` folder, not the other way around.

**Comment by matt8100** [comment]
> The first login request should not include the credentials: 'include' property. Only subsequent requests to data APIs should include it.

What happens when you include it in the first request?

**Comment by harsimrat99** [comment]
Hi Matt, I think you are right that we should move the routes in the device folder to the api folder. I think there is a bit of confusion on how we have organised the route folders so that's why I was getting confused.

So just to confirm if you agree with me, let's propose the following organisation:

image


Let me know if anything is unclear.

**Comment by harsimrat99** [comment]
> > The first login request should not include the credentials: 'include' property. Only subsequent requests to data APIs should include it.
> 
> What happens when you include it in the first request?

Hi Matt,
I have confirmed that including the **credentials: 'include'** directive in fetch options in step 1 does not cause any errors. I tried this with no cookies (cleared browsing data) and with a previous cookie (after refreshing the page).

**Pull request merged**
